### ISSUE TITLE
Issues with long-press menu and m3u8 playlist functionality

### ISSUE THREAD

**Issue by pitanni** [AndreyPavlenko/Fermata#570]
Description:
I am experiencing two issues:

Long-press menu not appearing on added items:
On the Files page, when I long-press on an item I previously added (e.g., a URL), the menu does not appear. This prevents me from performing actions like deleting the added item.

m3u8 playlist not working:
I added an m3u8 playlist that works perfectly on my PC (using VLC), but it does not work in the app. I would like to understand why this happens and if there is a way to resolve it.

Device: Samsung Galaxy S24 FE

Steps to reproduce:

Long-press menu issue:

Add an item (e.g., a URL) to the Files page.
Long-press on the added item.
Observe that the menu does not appear.
m3u8 playlist issue:

Add a valid m3u8 playlist to the app.
Try to play the playlist.
Observe that it does not work as expected.
Expected behavior:

For the long-press issue: A context menu should appear, allowing me to delete or manage the added item.
For the m3u8 issue: The playlist should work as it does on VLC on my PC.
Actual behavior:

No menu appears when long-pressing the added item.
The m3u8 playlist does not play in the app.
Please let me know if you need additional details, logs, or sample files!

**Comment by AndreyPavlenko** [comment]
> the menu does not appear

I observed this issues on some devices. It occurs because the item could not only be long pressed, but also moved and some devices report item move instead of long press. Try pressing it accurately, without performing any movement.



> I added an m3u8 playlist that works perfectly on my PC (using VLC), but it does not work in the app. I would like to understand why this happens and if there is a way to resolve it.

What exactly does not work?

**Comment by pitanni** [comment]
Thank you for the reply!

Regarding the long-press issue, I will try pressing more accurately as suggested to see if it resolves the problem.

About the m3u8 playlist issue:
The playlist loads correctly, and the EPG data is also displayed without any issues. However, when I try to open a channel, the app immediately closes the stream without playing anything.

Let me know if you need any additional details or if there's a specific log I can provide to help debug this issue.

**Comment by AndreyPavlenko** [comment]
Have you tested when connected to the same WiFi as the PC with VLC?

**Comment by pitanni** [comment]
Yes, I have tested it while connected to the same WiFi network as the PC with VLC. The playlist works fine on the PC, but it also works directly on the phone through another app. This leads me to believe the issue might be specific to the app in question.

Let me know if there's anything else I can provide!

**Comment by AndreyPavlenko** [comment]
What's the error message? Have you tried to change the media engine?

**Comment by pitanni** [comment]
I have tried everything, including changing the media engine and even modifying the user agent, but unfortunately, nothing changes.

Is there any log I can generate or provide to help you better understand the issue? Let me know how I can assist further.

**Comment by AndreyPavlenko** [comment]
You can find the log in the app settings > other.

**Comment by pitanni** [comment]
Ok, the error is:
[22-12-24 22:09:08][WARN][main][me.aap.fermata.media.service.MediaSessionCallback.onEngineError(SourceFile:76)] Impossibile riprodurre m3ut:1:0:1:https://........./index.m3u8: Source error
z0.m: Source error
	at z0.I.h(SourceFile:55)
	at z0.I.handleMessage(SourceFile:342)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: w0.w: Response code: 403
	at x0.f.m(SourceFile:438)
	at w0.m.m(SourceFile:312)
	at w0.A.m(SourceFile:10)
	at F0.e.f(SourceFile:5)
	at P0.j.run(SourceFile:35)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

**Comment by AndreyPavlenko** [comment]
> Response code: 403

It means forbidden. For some reason, the server rejects the connection. Have you tried to change the user agent in the playlist settings? Try the same ua as VLC - VLC/3.0.20 LibVLC/3.0.20.
